#!/bin/bash
set -ex

get_latest_release() {
  curl --silent "https://api.github.com/repos/shlinkio/shlink/releases/latest" | # Get latest release from GitHub api
  grep '"tag_name":' |                                                           # Get tag line
  sed -E 's/.*"([^"]+)".*/\1/'                                                   # Pluck JSON value
}

if [[ ${SOURCE_BRANCH} == 'master' ]]; then
    SHLINK_RELEASE=$(get_latest_release)
else
    SHLINK_RELEASE=${SOURCE_BRANCH}
fi

docker build --build-arg SHLINK_VERSION=${SHLINK_RELEASE#?} -t ${IMAGE_NAME} .
